### ISSUE TITLE
Suggestion: Improve usability of configured materials lists

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/TownyResources#10]
Hi there!

Currently the category entries are implemented with JSON like format:

```
  offers:
 
    # This list shows the survey offer categories.
    # 
    # Each category is enclosed in curly brackets, and has 4 parts:
    # 1 - The name of the category (used for messaging)
    # 2 - The discovery weight of the category (used during discovery)
    # 3-  The base amount of the offer (in stacks)
    # 4-  The list of materials in the category
    categories: |
      {common_dirt, 25, 2, DIRT}, {gravel, 100, 1, GRAVEL}, {sand, 100, 2, SAND}, {common_rocks, 100, 2, STONE, COBBLESTONE}, {uncommon_rocks, 100, 1, DIORITE, ANDESITE, GRANITE}, {terracotta, 100, 0.5, TERRACOTTA}, {quartz, 100, 0.25, QUARTZ_BLOCK}, {prismarine, 100, 0.125, PRISMARINE}, {obsidian, 100, 0.125, OBSIDIAN}, {clay, 100, 1, CLAY_BALL}, {ice, 25, 1, ICE}, {snow, 25, 1, SNOWBALL}, {coal, 200, 1, COAL}, {iron, 200, 0.5, RAW_IRON}, {gold, 200, 0.25, RAW_GOLD}, {copper, 100, 0.25, RAW_COPPER}, {emeralds, 200, 0.25, EMERALD}, {diamonds, 200, 0.125, DIAMOND}, {redstone, 100, 1, REDSTONE}, {ancient_debris, 200, 0.0625, ANCIENT_DEBRIS}, {wood, 200, 2, OAK_LOG, SPRUCE_LOG, BIRCH_LOG, JUNGLE_LOG, ACACIA_LOG, DARK_OAK_LOG, OAK_WOOD, SPRUCE_WOOD, BIRCH_WOOD, JUNGLE_WOOD, ACACIA_WOOD, DARK_OAK_WOOD}, {wheat, 100, 1, WHEAT}, {carrots, 100, 1, CARROTS}, {potatoes, 100, 1, POTATOES}, {beetroots, 100, 1, BEETROOT}, {pumpkins, 100, 1, PUMPKIN_SEEDS}, {melon_slices, 100, 1, MELON_SLICE}, {cocoa_plants, 100, 1, COCOA_BEANS}, {kelp, 100, 1, KELP}, {bamboo, 100, 1, BAMBOO}, {cactus, 100, 1, CACTUS}, {mushrooms, 100, 1, BROWN_MUSHROOM, RED_MUSHROOM}, {apple_trees, 100, 0.125, APPLE}, {vines, 100, 0.25, VINE}, {fish, 100, 1, COD, SALMON, PUFFERFISH, TROPICAL_FISH}, {wool, 100, 0.5, WHITE_WOOL}, {gunpowder, 200, 0.25, GUNPOWDER}, {string, 100, 0.25, STRING}, {spider_eyes, 100, 0.25, SPIDER_EYE}, {feathers, 100, 0.25, FEATHER}, {leather, 100, 0.25, LEATHER}, {rabbit_hide, 100, 0.25, RABBIT_HIDE}, {rotten_flesh, 100, 1, ROTTEN_FLESH}, {bones, 100, 0.5, BONE}, {pork, 100, 0.25, PORKCHOP}, {mutton, 100, 0.25, MUTTON}, {beef, 100, 0.25, BEEF}, {chickens, 100, 0.25, CHICKEN}, {eggs, 100, 0.25, EGG}, {ender_pearls, 100, 0.125, ENDER_PEARL}
```

The whole category entries are squeezed into one line, which is not quite quick to read and edit.

I would be better if it's the original yaml list format, for example:

```
  offers:
 
    # This list shows the survey offer categories.
    # 
    # Each category is enclosed in curly brackets, and has 4 parts:
    # 1 - The name of the category (used for messaging)
    # 2 - The discovery weight of the category (used during discovery)
    # 3-  The base amount of the offer (in stacks)
    # 4-  The list of materials in the category
    categories:
      - common_dirt:25:2:DIRT
      - gravel:100:1:GRAVEL
      - sand:100:2:SAND
```

Or, it would be better if each reload will not **overwrite** the config file... so that the user can add new lines to the category entries, for example:

```
  offers:
 
    # This list shows the survey offer categories.
    # 
    # Each category is enclosed in curly brackets, and has 4 parts:
    # 1 - The name of the category (used for messaging)
    # 2 - The discovery weight of the category (used during discovery)
    # 3-  The base amount of the offer (in stacks)
    # 4-  The list of materials in the category
    categories: |
      {common_dirt, 25, 2, DIRT},
      {gravel, 100, 1, GRAVEL},
      {sand, 100, 2, SAND},
      {common_rocks, 100, 2, STONE, COBBLESTONE},
      ...
```

But I prefer my first suggestion because it allows the user to **comment out** some of the category entries in between without breaking the whole "categories" string entry, like so:

```
  offers:
 
    # This list shows the survey offer categories.
    # 
    # Each category is enclosed in curly brackets, and has 4 parts:
    # 1 - The name of the category (used for messaging)
    # 2 - The discovery weight of the category (used during discovery)
    # 3-  The base amount of the offer (in stacks)
    # 4-  The list of materials in the category
    categories:
      - common_dirt:25:2:DIRT
      # - gravel:100:1:GRAVEL
      - sand:100:2:SAND
```

**Comment by Goosius1** [comment]
Hi,

- On the list editability
  - These lists should not reset to defaults on reload.
  - Editability of the materials lists is an essential feature of the plugin.
    - This has been working fine on my local server.
    - Also other servers have been editing and saving the lists without issue.
  - Can you check this again on your server please? - and if it does reset, pls include server logs
 
- On changing the lists to a standard yaml list format
  - That looks like a good idea!. 
  - Lets come back to that after we sort out your list modifiability

**Comment by Akiranya** [comment]
Oops! I added some new lines again and it did not reset this time. I must have been done something wrong.

**Comment by Akiranya** [comment]
So the list is quite reabable for now if I added a new line after each category 👍

**Comment by Akiranya** [comment]
Yaml list format looks not as demanding as before for now ... but yep it would be better if that's possible as commenting something out between the big category list would be a cool feature for server admins :)

**Comment by Goosius1** [comment]
- I've considered this
- And I think we'll stick with the existing format
- The main reason is that servers are already trialling *TownyResources*, and have already configured their materials lists.  If we change the format now, we will force them all to reconfigure.
- A secondary reason is that I fear people will find it more easy screw up their configurations of the yml lists 
- So since the lists are working ok now, I just don't think the payoff is worth the cost at this point.

**Comment by Akiranya** [comment]
That's alright! Since TR won't overwrite and reformat config.yml when reloading, this feature now seems not so demending for me actually. Also thanks for putting so much thinking into my suggestion :3
