### ISSUE TITLE
Suggestion: Localized item display names

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/TownyResources#11]
Hi there!

I'm here again to come up with a suggestion ;)

As the title. Currently the resource information on the town/nation's screen is only in English:

> Resources:
> Daily Production: 64 Oak Log, 32 Emerald
> Available For Collection: 64 Oak Log, 32 Emerald

I am not a native speaker and unfortunately not all players in my server can read the English names of all materials.

So the localized resource display names would really help those players :D

I am also a plugin developer and fortunately the easiest solution is to use a plugin called "LanguageUtils" to do the translation automatically. Here is the repo: https://github.com/NyaaCat/LanguageUtils and here is the usage example: https://github.com/MascusJeoraly/LangUtilsExample

**Comment by Goosius1** [comment]
Hi, this library is great!, but I have some questions about it:

1. For servers to get this to work, will they have to drop the jar into their plugin folders?
2. Or should maven just pull it in?
3. Or should I build it inside TownyResources ?
4. If **3** .... then can the size be reduced?.  It is currently 4 megabytes, which is almost twice as large as Towny

**Comment by Akiranya** [comment]
1. Yes they do
2. Need to add to maven pom.xml of this project as a dependency so that IDE can recognise it and TownyResources can be compiled
3. No. It's a plugin and it doesn't need to be shaded it into TownyResources to make a "fat" jar. If implemented smartly, only those who need this feature have to put LanguageUtil jar into their plugin folder.

---

As a developer, I understand that we always want a slim jar instead of fat one and want to reduce the extra stuff that a server admin has to install on their servers as much as possible. Making something optional really optional is always the best decision :)

I think there are basically two cases for this feature:

1. The server admin and their players are mainly English native speakers and they dont need this feature at all
2. The server admin and their players are NOT mainly English native speakers and they need this feature (like the players on my server)

My recommedation would be: If the server admin has put the LanguageUtil jar into their plugin folder, then TownyResources will use LanguageUtils to get the display names of materials. Otherwise, TownyResources will just directly get the display names.

If this feature were implemented this way, then those who want this feature could simply install LanguageUtils and those who don't could simlpy use the TownyResource the way as before.

**Comment by Goosius1** [comment]
Ok I think I get it, thanks for the info!. We'll go with your recommendation, makes sense!

**Comment by Goosius1** [comment]
Nearly done...

![image](https://user-images.githubusercontent.com/50219223/131704497-668c10d2-cda3-46d6-b3ca-323e1a1b5ba2.png)
