### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile

### ISSUE THREAD

**Issue by Justman100** [TownyAdvanced/TownyResources#138]
With the latest fix, now comes this:

[log.txt](https://github.com/TownyAdvanced/TownyResources/files/13952741/log.txt)

**Comment by LlmDl** [comment]
Ok let me see about re-adding one of the dependencies I removed. I did not receive any errors on my end.

**Comment by Justman100** [comment]
> I did not receive any errors on my end.

Have used this commands:

```
git init
git pull https://github.com/TownyAdvanced/TownyResources
mvn install
```

**Comment by LlmDl** [comment]
I will try to update the MMOItems api, it is probably out of date

**Comment by LlmDl** [comment]
Try building master branch now

**Comment by Justman100** [comment]
> Try building master branch now

Working!
