### ISSUE TITLE
Minor issue with LanguageUtils

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/TownyResources#15]
First thank you very much for considering my suggestion!

Just a minor issue to report: the localized material display currently does not work properly - it currently shows the names in English even tho LangUtils is installed.

---

Fortunately, I **probably** have found the reason ... should be easy to fix - may need to double-check:

The plugin name defined in the plugin.yml of LanguageUtils is "LangUtils": https://github.com/NyaaCat/LanguageUtils/blob/12b321f973b8ab95d0d6863e5a0850370541d0d4/src/main/resources/plugin.yml#L1

But the plugin name specified in TownyResources is "LanguageUtils": https://github.com/TownyAdvanced/TownyResources/blob/f7636a5eeef24786ad1e8efbf6e847819054e7a2/src/main/java/io/github/townyadvanced/townyresources/TownyResources.java#L193

So it leads to TownyResources not being able to detect whether LangUtils is really installed or not.

> Sorry for the confusion in [the first place](https://github.com/TownyAdvanced/TownyResources/issues/11) as I referred to the language utils plugin as "LanguageUtils" o.o

---

Second minor issue is that the latest version of LangUtils is 2.5-SNAPSHOT as can be seen in the maven repo: https://ci.nyaacat.com/maven/com/meowj/LangUtils/. Could you update the dependency to the latest version? Nothing about the code should need to be changed :3

**Comment by Goosius1** [comment]
- This was working for me. Look: 
![image](https://user-images.githubusercontent.com/50219223/131804131-7f650b79-aa11-441c-99d3-d8f56203ed25.png)

- It was definitely detecting the plugin. Because I have multiple logic in there which ensure it won't even TRY to translate unless it detects the plugin.

- Can you double check what's going on? We wouldn't want to accidentally break it for users (like me) for whom it currently seems to works fine. Where in the game were you seeing the non-localized names?

**Comment by Akiranya** [comment]
I can at least confirm that LangUtils works during the test because one of my plugin is using LangUtils to get localized display names.

**Comment by Akiranya** [comment]
I'm gonna compile TownyResources on my own and test it to see if my assumption is correct. I'll let you know later on :D

**Comment by Akiranya** [comment]
Hi, I've just confirmed that it's because of the wrong plugin name specified in here:

https://github.com/TownyAdvanced/TownyResources/blob/f7636a5eeef24786ad1e8efbf6e847819054e7a2/src/main/java/io/github/townyadvanced/townyresources/TownyResources.java#L193

I've also made a PR to fix it. I've tested it and it worked :3 Can you check it out?

**Comment by Akiranya** [comment]
Btw this is the LangUtils jar I was using during my test: https://ci.nyaacat.com/job/LanguageUtils/job/1.17/

**Comment by Goosius1** [comment]
- Ah, I think the Jar was the source of the problem
- I only had the github link
- So I was getting the Jar here this: https://github.com/NyaaCat/LanguageUtils/releases
- I will check out that PR yes

**Comment by Goosius1** [comment]
- PR merged, thanks!
- I will release this in a new version later today probably. (and update the install guide to point to the CI job)

**Comment by Goosius1** [comment]
Closed as done
