### ISSUE TITLE
Compatibility with Illegal Stack.

### ISSUE THREAD

**Issue by Mint-101** [TownyAdvanced/TownyResources#158]
Whenever players collect resources from their town items should not be stacked over 64. Whenever I collect resources from my town I'll get stacks of 99 items and illegal stack will have a problem with it.

**Comment by LlmDl** [comment]
TownyResources uses the max stack size for each material. If you have abnormal stack sizes it is because another plugin is modifying the max-stack size for a material and not returning it to normal after giving the player some items.

**Comment by Mint-101** [comment]
What kind of plugins would be causing this issue? I can't think of any that would change the max-stack-size for items. I have a full I can give you if that will help.

**Comment by LlmDl** [comment]
I do not know what it could be, lots of plugins could be causing it.
