### ISSUE TITLE
Suggestion: MMOItems compability

### ISSUE THREAD

**Issue by kibubek** [TownyAdvanced/TownyResources#16]
It would be neat to have compatibility with MMOItems as resources.

Here is the latest API documentation I found.
https://git.mythiccraft.io/mythiccraft/mmoitems/-/wikis/Main%20API%20Features

**Comment by Goosius1** [comment]
- Hi, I had a look at this, but didn't find many example in the documentation for resources
- The closest things I could find were "recipe ingredients" and "custom blocks", but the wiki provided no examples of these.
  - https://git.mythiccraft.io/mythiccraft/mmoitems/-/wikis/Recipe%20Ingredients
  - https://git.mythiccraft.io/mythiccraft/mmoitems/-/wikis/Custom%20Blocks
- So, although I'm sure *TR* could have have some use in this area, my question is, is it worth the bother for me?. How many servers are actually using custom blocks & ingredients in such a way that would make it useful for towns to produce them ?

**Comment by Goosius1** [comment]
Closed as no response from ticket holder

**Comment by Snowy2174** [comment]
I'm so sorry to bother y'all but was about to open a ticket on a similar topic, wondered if  it was best to mention it here?

**Comment by LlmDl** [comment]
MythicMobs item integration was added in teh latest release @Snowy2174 is that what you wanted?

**Comment by Snowy2174** [comment]
> MythicMobs item integration was added in teh latest release @Snowy2174 is that what you wanted?

Not particularly, I was referring to MMOItems but thanks greatly for your response.
