### ISSUE TITLE
Suggestion: Survey confirmation message shows the number of residents required to extract the resource

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/TownyResources#28]
Some players become angry or confused when they discover that they do not have enough residents to extract a resource they surveyed. Although this is arguably their fault, it would be nice if the `/tr survey` confirmation message included the number of residents needed to extract the resource that is to be discovered, e.g:

> You are about to survey the town of X for its level Y resource. This will cost Z. The town needs at least R residents to extract this resource.

**Comment by Goosius1** [comment]
Done.
- Do you have capacity to test the fix?
- It is on branch TR-28
- Otherwise I can test it later today
