### ISSUE TITLE
Cannot run commands

### ISSUE THREAD

**Issue by Acult** [TownyAdvanced/TownyResources#36]
Using latest Towny and latest Towny Resources build (0.0.16)
Using paper fork 1.16.5

When i type a command, like /tra or /townyresources, nothing happens and no errors gets displayed in console

**Comment by LlmDl** [comment]
Stop your server. Start your server, let it load completely, then stop it. A new latest.log will be created in your logs folder. Please upload it to a paste-service like https://paste.ee/ (say !paste if you need links.) Describe your problem to the channel. Someone will answer you when they are available.
