### ISSUE TITLE
Request: Add /tre as /tr alias

### ISSUE THREAD

**Issue by savdbroek** [TownyAdvanced/TownyResources#39]
Hi,

I currently have Citizens installed and sadly this also has a /tr (/traits) command. It takes priority over Towny Resource so we're not able to do /tr towncollect. I've tried removing the /tr alias from Citizens (as a test) but that prevents Citizens from starting at boot. 

Are you able to add /tre (or something similar) as an alias to /townyresources. I know this can easily be done within the commands.yml of spigot. But I figure I won't be the only one with this issue.

If not, no problem.

Kind regards,

DarkBoomba

**Comment by LlmDl** [comment]
The server commands.yml is what you want to use to make /tr point to /townyresources. This does not require you to modify every citizens jar you upload.
