### ISSUE TITLE
Improve code pattern for action bar usage

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/TownyResources#42]
### DESCRIPTION
- Currently the action bar messages (for limits) are triggered using an "md_5" library which does not work on some MC servers (e.g. CraftBukkit 1.16.5).
- There is now code in place to prevent this erroring, by simpply catching and ignoring the load error. 
- However It would be best to do these action bar messages in the same way Towny does, via the "adventure" library

### EXPECTED
- Adjust the "ActionBarUtil" class to use the adventure library
- See how the Towny CustomListener class uses it
- For more info see https://docs.adventure.kyori.net/
- Also note that to get it working, you may need to "shade" it, in the same way that Towny does
- Or possibly make use of Towny's shaded version....
- OR **perhaps add a generic method to TownyMessaging for the action bar. Then TownyResources could simply call that.**
- Investigate and find the best option

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commit/1eb816cc2d0d9eeb1aa4e224822c44ae96019c34 adds action bar and boss bar usage, allowing this to be part of SiegeWar post-0.97.3.1.
