### ISSUE TITLE
The plugin doesn't work with slimefun 4?

### ISSUE THREAD

**Issue by Peskdt** [TownyAdvanced/TownyResources#44]
[message.txt](https://github.com/TownyAdvanced/TownyResources/files/7266334/message.txt)

![imagen](https://user-images.githubusercontent.com/91406867/135603956-00a8d493-fd6b-4f32-8ed9-5ad525389595.png)

**Comment by Goosius1** [comment]
Hi can you test if this works please ?
[TownyResources-0.1.2.zip](https://github.com/TownyAdvanced/TownyResources/files/7268946/TownyResources-0.1.2.zip)

**Comment by Peskdt** [comment]
[startlog 2.txt](https://github.com/TownyAdvanced/TownyResources/files/7270221/startlog.2.txt)

**Comment by Goosius1** [comment]
- That's  good, no slimefun errors.
- To fix this, remove those materials which aren't on your server, then restart.
- Let me know how that goes

**Comment by Peskdt** [comment]
Done, it works perfectly.
![imagen](https://user-images.githubusercontent.com/91406867/135701525-7b7396ea-8d03-48c6-bf8f-4704e84f3bbe.png)
