### ISSUE TITLE
Make biomes influence resources

### ISSUE THREAD

**Issue by MidnightSugar** [TownyAdvanced/TownyResources#48]
I have an idea for this. Maybe you could have the biome influence what resources you can attain. Maybe grasslands can give more animals and be farming towns, oceans/rivers can give fish, mountains can give more ores, forests wood of its type.

People can create an outpost in a location based on what resource they want to harvest.

**Comment by LlmDl** [comment]
This will likely be looked into in earnest when custom plot types are added to Towny, and a survey plot can be added.

**Comment by Goosius1** [comment]
- In practice, towns would create a temporary outpost in its prefererred biome, move the homeblock there, do the survey, and then delete the outpost.
- Thus the suggested feature as it stands is essentially a convoluted way of letting towns choose their resources.
- Options:
  - A. If you want to allow towns to choose their resource types, I suggest to do it in a less convoluted way, simply via a choice attached to the survey command.
  - B. If on the other hand, you want the common-sense location of the town to automatically influence the selection, then I suggest this:  When the survey is done,  find the biome of EVERY town block.  Crunch the numbers to give the probability of finding particular resources. This specific option would still be open to abuse though,  by people creating huge temporary and empty outpost regions in their desired biomes. So this needs further design work.

**Comment by MidnightSugar** [comment]
Why would you need to move your homeblock. I am confused. Can't you set survey plots anywhere, but if plot is unclaimed or taken over then you lose the resources from it. But the amount of resource plots is restricted by the amount of residents in the town since they need to "work" the plots.

**Comment by LlmDl** [comment]
This is something I think has to be tied to a survey plot. TR can make it so that those plots are expensive to set, and could prevent unclaiming those plots as well. It's also something that could be limited in number available.

**Comment by MidnightSugar** [comment]
Also what I had in mind was that each biome wouldn't just give one resource. It would just have additional biome resources.

So there would be your standard resources like ores, which are found in every biome. With a bonus to some resources in certain biomes, mesa could have more gold ore. Deserts could produce much more sand. Birch forests much more birch wood.

The plots will have a cost to create. Plus they need to be worked, so the more residents the higher the production, and if you start losing members you will get a penalty to production. 

What do you guys think of that?

**Comment by LlmDl** [comment]
Could be very interesting, the survey plots system is something I'd like to add when I have the time.
