### ISSUE TITLE
[Small Suggestion] Changing TownyResources title when loading.

### ISSUE THREAD

**Issue by ConaII** [TownyAdvanced/TownyResources#50]
![image](https://user-images.githubusercontent.com/72966048/141661052-ffdf38f7-d36b-4f6e-8cfa-f65263b0df95.png)

https://github.com/TownyAdvanced/TownyResources/blob/master/src/main/java/io/github/townyadvanced/townyresources/TownyResources.java#L119

to:
https://pastebin.com/5vK535Wy

(I already did this for my jar)

I think the big one is a bit too big, idk, just saying

**Comment by LlmDl** [comment]
It is too long to fit in the console, you are correct.

**Comment by LlmDl** [comment]
![Capture](https://user-images.githubusercontent.com/879756/141661693-abfcfabc-6ae3-4e0d-b27a-6c3f92ebe434.PNG)
Is a fair bit closer [to this classic](https://cdn.2kgames.com/web/civilization.com/images/civilization-1/civ1_logo.png).

**Comment by ConaII** [comment]
Yoo, that's sick

**Comment by LlmDl** [comment]
https://patorjk.com/software/taag/ is the generator I've used for many of the projects that have ascii art.
