### ISSUE TITLE
[QUESTION] What is the difference between two "categories"

### ISSUE THREAD

**Issue by Bladesunder** [TownyAdvanced/TownyResources#55]
While inside the config.yml, I was confused why there were 2 different "categories". One listed under "resource_extraction_limits" and another under "offers" which is under "town_resources". What is the difference between the two lists and why do they contain different bits of information?

**Comment by LlmDl** [comment]
The extraction limits categories are the the lists of blocks that each player is limited to for harvesting, the number being a stack.

The resources categories are what players' towns can receive when they survey.

**Comment by Bladesunder** [comment]
Thanks for clarifying!
