### ISSUE TITLE
Make resources dependent on the biome of the homeblock

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/TownyResources#62]
Making town resources dependent on the biome of the homeblock would add further uniqueness to each town.  Towns in a Soul Sand Valley might be able to produce Soul Sand where others would not;  while towns in a Mesa might be able to produce extra Raw Gold, or Terracotta.  This wouldn't be fixed to a single resource per biome -- rather, each biome would have a list of valid resources.  For a Birch Forest, for example, the resources might be Birch Logs, Honey/Honeycomb, Rose/Lilac/Peony/Lily.  There would also be a set of common resources for each world that could be selected as well.  Nether towns would have, for example, Netherrack, Blackstone, etc;  and Overworld towns would have Cobblestone, Dirt, etc.

This issue is more of an idea than an exact path to implementation;  nevertheless, I do hope it's something you see some value in.

**Comment by ElMoha943** [comment]
+1 Really want this

**Comment by LlmDl** [comment]
This is going to be based on the location of the Survey plots instead of the homeblock.

**Comment by Caleston** [comment]
> This is going to be based on the location of the Survey plots instead of the homeblock.

Wouldn't that be too easy to bypass? Towns could just claim outposts or in various biomes in order to survey in chunks that don't really relate to much of their town. 
Homeblock would be a more fixed option and could promote trading between towns that are in different biomes.
