### ISSUE TITLE
[BUG] TownyResources resets Raw_Iron to 0 instead of 32 

### ISSUE THREAD

**Issue by Dynamite99** [TownyAdvanced/TownyResources#65]
Ways to reproduce:

Create a town and get raw iron as the resource, it will display that they have obtained 32 iron every day when they first use the command, but after some time the /town menu it will show 0. It will also stay at 0 after editing the metadata when the server is online using the /townyadmin reload all command and when the file is edited in offline. 

(for the town losing iron) Town metadata: https://pastebin.com/dAh8LXfE (this town's 2nd resource reset to 0)
(for the town losing ancient_debris: Town Metadata: https://pastebin.com/tLe9Wu9A (this town's 3rd resource reset to 0)
(for the town losing 2 resources) Town metadata: https://pastebin.com/sBjbykv4 (this towns 2nd and 3rd resource reset to 0)
TownyResources config: https://pastebin.com/kNAvd45M
Startup Config: https://pastebin.com/7k3MFjPd

Things I tried to look into: 
- Initially I thought it was only the second resource resetting, but it eventually showed the third would too
- I thought possibly it was only the ores, but it ended up being things like dirt (shown in the 3rd town)
- Editing the metadata had no effect on any of these towns
- I thought a possible loss of land plots may affect it, but none of these towns unclaimed any land during this time. (if anything their levels raised)

**Comment by LlmDl** [comment]
I believe this is due to the town not meeting the requirements for that tier, ie they don't have enough residents or land or town_level. If you're still seeing this behaviour please check that the towns still meet the requirements to get the resource offer, then please reopen this ticket with more details if they should be getting their offers.
