### ISSUE TITLE
Suggestion: Add cooldown for sending warning message

### ISSUE THREAD

**Issue by Akiranya** [TownyAdvanced/TownyResources#7]
As the title.

Similar for the Towny land protection: if the player breaks something in the town land in which the player has no permission, the "no permission" message won't appear each time when the player tries to break the thing.

**Comment by Goosius1** [comment]
- Hi. There already is a cooldown between these limit messages
- It is currently hardcoded to 5 seconds
- Are you thinking the cooldown should be longer?

**Comment by Akiranya** [comment]
No 5s is all good but an option to modify it would be better if possible!

Ok so the thing is I'm just gonna install this plugin on my server because the idea really attracts me :). But I'm kinda worried about if the player has reached the resource limit, would this plugin send warning message too often. So I just quickly looked at the source code of "sending warning messages" and didn't find anything related to cooldown. I must have missed something. Sorry for opening this trivial issue ...

**Comment by Goosius1** [comment]
No problem, and the configurable time idea is a good one thanks. I will implement that shortly.

**Comment by Goosius1** [comment]
Closed as implemented, in https://github.com/TownyAdvanced/TownyResources/pull/8
