### ISSUE TITLE
[Feature Request] Command to re-roll the resources of a specific town

### ISSUE THREAD

**Issue by galacticwarrior9** [TownyAdvanced/TownyResources#75]
There is currently a command to re-roll the resources of *all* towns: `/tra reroll_all_resources`

What would also be useful is a command to re-roll the resources of a *specific* town, e.g. `/tra reroll_town_resources <town name>`, or something along those lines.

**Comment by ElMoha943** [comment]
It would also be nice to have a `/tr reroll` for mayors to use, with a $ cost ofc.
