### ISSUE TITLE
Problem enabling Mythic Integration

### ISSUE THREAD

**Issue by Peskdt** [TownyAdvanced/TownyResources#85]
14.04 10:02:30 [Server] INFO ------------------------------------------------------------------------
14.04 10:02:30 [Server] INFO Enabling TownyResources v0.2.2
14.04 10:02:30 [Server] INFO --------------- Goosius' --------------  
14.04 10:02:30 [Server] INFO ╔╦╗┌─┐┬ ┬┌┐┌┬ ┬  ╦═╗┌─┐┌─┐┌─┐┬ ┬┬─┐┌─┐┌─┐┌─┐
14.04 10:02:30 [Server] INFO ║ │ │││││││└┬┘  ╠╦╝├┤ └─┐│ ││ │├┬┘│  ├┤ └─┐
14.04 10:02:30 [Server] INFO ╩ └─┘└┴┘┘└┘ ┴   ╩╚═└─┘└─┘└─┘└─┘┴└─└─┘└─┘└─┘
14.04 10:02:30 [Server] INFO SiegeWar Integration Enabled
14.04 10:02:30 [Server] INFO DynmapTowny Integration Enabled
14.04 10:02:30 [Server] INFO Slimefun Integration Enabled
14.04 10:02:30 [Server] WARN java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
14.04 10:02:30 [Server] WARN at TownyResources-0.2.2(1).jar//io.github.townyadvanced.townyresources.TownyResources.setupIntegrationsWithOtherPlugins(TownyResources.java:206)
14.04 10:02:30 [Server] WARN at TownyResources-0.2.2(1).jar//io.github.townyadvanced.townyresources.TownyResources.loadAll(TownyResources.java:65)
14.04 10:02:30 [Server] WARN at TownyResources-0.2.2(1).jar//io.github.townyadvanced.townyresources.TownyResources.onEnable(TownyResources.java:38)
14.04 10:02:30 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
14.04 10:02:30 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
14.04 10:02:30 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
14.04 10:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
14.04 10:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
14.04 10:02:30 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736)
14.04 10:02:30 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:353)
14.04 10:02:30 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1233)
14.04 10:02:30 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
14.04 10:02:30 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
14.04 10:02:30 [Server] WARN Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
14.04 10:02:30 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
14.04 10:02:30 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
14.04 10:02:30 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
14.04 10:02:30 [Server] WARN ... 13 more
14.04 10:02:30 [Server] ERROR Problem enabling mythic mobs
14.04 10:02:30 [Server] INFO Lang: english.yml v0.07 loaded.

**Comment by LlmDl** [comment]
This might already be fixed by #83

**Comment by Peskdt** [comment]
So it will be fixed in the next update?

**Comment by LlmDl** [comment]
I think @Goosius1 might have something that had to be done to it still, but I don't recall if there's any hold ups.

**Comment by Goosius1** [comment]
Hi. 

I did patch the problem on the master brach just now, so that TR will load without crashing.

However to actually allow the MM categories to be used again, will need more investigation.
