### ISSUE TITLE
More Resources Than Inventory Can Hold So Produced Resources Are Lost

### ISSUE THREAD

**Issue by EcoSMP** [TownyAdvanced/TownyResources#92]
If a town/nation produces more resources than the player collecting them can hold in their inventory, those resources are simply lost when the player uses the collection commands.

**Comment by LlmDl** [comment]
It never places them into the inventory, it drops them on the ground at the player's location. Anything that doesn't fit would just be on the ground.

**Comment by LlmDl** [comment]
It is some other plugin entirely I imagine.

**Comment by LlmDl** [comment]
It's not coded that way. I'm usually doing things that sponsors want and/or things I find interesting.
