### ISSUE TITLE
Too Many Resources To Collect

### ISSUE THREAD

**Issue by EcoSMP** [TownyAdvanced/TownyResources#95]
Nations and towns produce far more than one inventory worth of resources each day. They are supposed to drop onto the ground, and some of them do, but nations lose more than half of their produced resources oftentimes even when they drop onto the ground. Below are a few potential solutions we have thought of. We are hoping you to get your opinion on which one of these would be the best option to pursue.

1. Let players collect a single resource at a time instead of all of them at once. (/tr towncollect [resource_name] /tr nationcollect [resource_name]) This way they can collect each resource individually and they really wouldn't ever need more than an inventory worth unless they have occupied a crazy amount of towns. This would require a change either by you or we can have our dev team do it.

2. Use mythicmobs to create custom "voucher" items so when collecting resources, the player is actually collecting a small number of vouchers that can then be redeemed for the actual resources using a separate shop/plugin. We can do this on our own right now, we are just asking if you see any potential issues doing things this way and if you have any suggestions on how to better pursue this.

3. let us connect a console command to the resources when they are being collected instead of just the items. Upon collection, the plugin doesn't just throw a bunch of items on the ground. Instead, it runs a command in the console which is set per resource in the config. This would allow users to do almost anything they can think of instead of just being limited to dropping a single inv worth of default items at once.

**Comment by LlmDl** [comment]
Interesting solutions for something that results from your server clearing item drops. 

I'm currently focusing on this I find fun, fixing bugs in my plugins and doing things for sponsors.

It's good to have this on the board though, someone might help solve this with a pull request.

**Comment by LlmDl** [comment]
The plugin drops all of the items onto the ground. They are not put into the player's inventory by TownyResources.

If there's more than an inventory's worth, I don't see why a player wouldn't do it on top of a hopper floor or something when they know they will not be able to pick it up.

You're confusing my limited time with laziness. I currently do not make enough money from sponsors to put lots of time into Towny and its plugins. I have been doing this for 10+ years and it has never paid close to how much time I put into it.

As I have said, I focus on things I find interesting, things which are bugs and things my sponsors think are good. It's a good idea to support the developers you rely upon.

**Comment by LlmDl** [comment]
It's not that I dont see an issue. I am not prioritizing this issue. The plugin is open source and anyone with competent skills can make a pull request.

TownyResources is a plugin created by Goosius, who has retired from plugin development. I am maintaining his plugins in his absence.

Again, I am not obligated to make changes and the fact is, the admin community generally does not support open source plugin developers to do the work they demand.

I made my latest PR to this repo just yesterday, I have lots of work to do in all of the plugins I work on. I also have real life obligations.

The attitude you've chosen to take, trying to strong arm me into feeling like I need to fix this, is not appealing either.

**Comment by LlmDl** [comment]
If I were to put time into this I would create a system that just filled up the inventory of the command-runner with the amount they can carry. 

The feelings you appear to be reading into my responses are inaccurate. Telling me I am leaving short, rude and unhelpful responses is not helping.

**Comment by LlmDl** [comment]
I would go with option 1, as it would support servers that don't have mythic mobs installed. It would only require that you match the name entered with something in the resources that are available. Material-name-matching code might already be present in the code base.

The voucher system might be simple for someone well-versed in MM's API though. I haven't dabbled much in it aside from getting it working in TR last time it broke.
