### ISSUE TITLE
Add constant resources category

### ISSUE THREAD

**Issue by Peskdt** [TownyAdvanced/TownyResources#99]
Add a new **offer source's category** that does not increase by the **productivity_percentage_per_resource_level**.

**Comment by LlmDl** [comment]
I'm not sure I understand what you mean. Can you explain it like my brain is made of cheese with 128mb of ram stuck in it?

**Comment by Peskdt** [comment]
I mean create a new type of resources in the offers config 
![imagen](https://user-images.githubusercontent.com/91406867/201172597-b613bc94-f2a0-4cff-9a23-9fbbb353cf82.png)
that doesn't be affected by the productivity_percentage_per_resource_level
![imagen](https://user-images.githubusercontent.com/91406867/201172789-58ead3fc-9e35-48d3-b33a-d30f17378fc0.png)
 In this way, there would be resources that (regardless of the town level) would always produce the same amount of resources. Useful for custom objects, or to always control the amount of some resources coming into the server.
